import Head from 'next/head';
import { PropsWithChildren } from 'react';

import Footer from './Footer';
import Navbar from './Navbar';

interface LayoutProps {
  currentPage: string;
}

const Layout: React.FC<PropsWithChildren<LayoutProps>> = ({
  children,
  currentPage,
}) => {
  return (
    <div
      className="w-full m-auto flex flex-col items-center justify-center min-h-screen opening-box-animate-paddin text-white overflow-hidden md:overflow-visible"
      style={{ maxWidth: '1200px' }}
    >
      <Head>
        <title>{`Hey, Let's go`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5 w-full flex-1 text-center">
        <div className="hidden sm:block z-100">
          <Navbar currentPage={currentPage} />
        </div>
        {children}
      </main>

      <Footer />
    </div>
  );
};

export default Layout;
